project_module3/app_praes/urls.py
from django.urls import path 
from rest_framework.authtoken import views
from .apiviews import TemperaturaAPI, HumedadAPI, PresionAtmosfericaAPI, MaterialParticuladoAPI, \
                      NO2API, PolvoAPI, O3API, SO2API, COAPI, CO2API, MetanoPropanoCOAPI, \
                      LuzUVAPI, MaterialOrganicoAPI, CH4API, AnemometroAPI, \
                      CrearUsuarioAPI, LoginView, SensoresAPI

from rest_framework_swagger.views import get_swagger_view
from .views import index, medicion_actual, monitoreo_lecturas, control_ESP32

app_name = "app_praes"
schema_view = get_swagger_view(title='Estructura API')

urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('usuario/', CrearUsuarioAPI.as_view(), name="crear-usuario"),
    path('docs/', schema_view, name="documentacion"),
    path('temperatura/', TemperaturaAPI.as_view(), name="praes-temperatura"),
    path('humedad/', HumedadAPI.as_view(), name="praes-humedad"),
    path('presion-atmosferica/', PresionAtmosfericaAPI.as_view(), name="praes-presion-atmosferica"),
    path('material-particulado/', MaterialParticuladoAPI.as_view(), name="praes-material-particulado"),
    path('no2/', NO2API.as_view(), name="praes-no2"),
    path('polvo/', PolvoAPI.as_view(), name="praes-polvo"),
    path('o3/', O3API.as_view(), name="praes-o3"),
    path('so2/', SO2API.as_view(), name="praes-so2"),
    path('co/', COAPI.as_view(), name="praes-co"),
    path('co2/', CO2API.as_view(), name="praes-co2"),
    path('metano-propano-co/', MetanoPropanoCOAPI.as_view(), name="praes-metano-propano-co"),
    path('luz-uv/', LuzUVAPI.as_view(), name="praes-luz-uv"),
    path('material-organico/', MaterialOrganicoAPI.as_view(), name="praes-material-organico"),
    path('ch4/', CH4API.as_view(), name="praes-ch4"),
    path('anemometro/', AnemometroAPI.as_view(), name="praes-anemometro"),
    path('index/', index, name="index-praes"),
    path('medicion_actual/', medicion_actual, name="medicion-actual"),
    path('monitoreo_lecturas/', monitoreo_lecturas, name="monitoreo-lecturas"),
    path('control_kit/', control_ESP32, name="control-kit"),
    path('sensores/', SensoresAPI.as_view(), name="sensores-API"),
]

project_module3/paws/urls.py
from django.urls import path 
from . import views

app_name = "paws"
urlpatterns = [
    path("index", views.index, name="index-paws"),
    path("register", views.register, name="register"),
]

project_module3/project_module3/urls.py
from django.contrib import admin
from django.urls import path, include
from app_sensado import views


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('app_sensado/', include('app_sensado.urls', namespace='app_sensado')),
    path('app_praes/', include('app_praes.urls', namespace="app_praes")),
    path('paws/', include('paws.urls', namespace="paws")),
    path('nariz_electronica/', include('nariz_electronica.urls', namespace="nariz_electronica")),
    path('E3Tratos/', include('E3Tratos.urls', namespace="E3Tratos")),
    path('', views.main_index, name='main-index'),
    path('accounts/', include('django.contrib.auth.urls')),
]

project_module3/app_praes/models.py
from django.db import models
# Create your models here.

class Departamento(models.Model):
    nombre_departamento = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre_departamento

class Ciudad(models.Model):
    nombre_ciudad = models.CharField(max_length=50)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre_ciudad
        
class Colegio(models.Model):
    nombre_colegio = models.CharField(max_length=100)
    telefono = models.CharField(max_length=50, unique=True)
    nombre_rector = models.CharField(max_length=50)
    correo_rector = models.EmailField(max_length=254)
    direccion_colegio = models.CharField(max_length=50)
    ciudad = models.ForeignKey(Ciudad, on_delete=models.CASCADE)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre_colegio

class Kit(models.Model):
    nombre_kit = models.CharField(max_length=50)
    colegio = models.ForeignKey(Colegio, on_delete=models.CASCADE)
    observaciones = models.CharField(max_length=200, null=True)
    ubicacion_kit = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre_kit

class Sensores(models.Model):
    nombre_sensor = models.CharField(max_length=50)
    kit = models.ForeignKey(Kit, on_delete=models.CASCADE)
    observaciones = models.CharField(max_length=150, null=True)

    def __str__(self):
        return self.nombre_sensor

class Temperatura(models.Model):
    fecha = models.DateTimeField(auto_now=False, auto_now_add=False)
    valor = models.FloatField()
    sensor = models.ForeignKey(Sensores, on_delete=models.CASCADE)


class Humedad(models.Model):
    fecha = models.DateTimeField(auto_now=False, auto_now_add=False)
    valor = models.FloatField()
    sensor = models.ForeignKey(Sensores, on_delete=models.CASCADE)

class PresionAtmosferica(models.Model):
    fecha = models.DateTimeField(auto_now=False, auto_now_add=False)
    valor = models.FloatField()
    sensor = models.ForeignKey(Sensores, on_delete=models.CASCADE)

class MaterialParticulado(models.Model):
    fecha = models.DateTimeField(auto_now=False, auto_now_add=False)
    valor = models.FloatField()
    sensor = models.ForeignKey(Sensores, on_delete=models.CASCADE)

class NO2(models.Model):
    fecha = models.DateTimeField(auto_now=False, auto_now_add=False)
    valor = models.FloatField()
    sensor = models.ForeignKey(Sensores, on_delete=models.CASCADE)

class Polvo(models.Model):
    fecha = models.DateTimeField(auto_now=False, auto_now_add=False)
    valor = models.FloatField()
    sensor = models.ForeignKey(Sensores, on_delete=models.CASCADE)

class O3(models.Model):
    fecha = models.DateTimeField(auto_now=False, auto_now_add=False)
    valor = models.FloatField()
    sensor = models.ForeignKey(Sensores, on_delete=models.CASCADE)

class SO2(models.Model):
    fecha = models.DateTimeField(auto_now=False, auto_now_add=False)
    valor = models.FloatField()
    sensor = models.ForeignKey(Sensores, on_delete=models.CASCADE)
    
class CO(models.Model):
    fecha = models.DateTimeField(auto_now=False, auto_now_add=False)
    valor = models.FloatField()
    sensor = models.ForeignKey(Sensores, on_delete=models.CASCADE)

class CO2(models.Model):
    fecha = models.DateTimeField(auto_now=False, auto_now_add=False)
    valor = models.FloatField()
    sensor = models.ForeignKey(Sensores, on_delete=models.CASCADE)

class MetanoPropanoCO(models.Model):
    fecha = models.DateTimeField(auto_now=False, auto_now_add=False)
    valor = models.FloatField()
    sensor = models.ForeignKey(Sensores, on_delete=models.CASCADE)

class LuzUV(models.Model):
    fecha = models.DateTimeField(auto_now=False, auto_now_add=False)
    valor = models.FloatField()
    sensor = models.ForeignKey(Sensores, on_delete=models.CASCADE)

class MaterialOrganico(models.Model):
    fecha = models.DateTimeField(auto_now=False, auto_now_add=False)
    valor = models.FloatField()
    sensor = models.ForeignKey(Sensores, on_delete=models.CASCADE)

class CH4(models.Model):
    fecha = models.DateTimeField(auto_now=False, auto_now_add=False)
    valor = models.FloatField()
    sensor = models.ForeignKey(Sensores, on_delete=models.CASCADE)

class Anemometro(models.Model):
    fecha = models.DateTimeField(auto_now=False, auto_now_add=False)
    valor = models.FloatField()
    sensor = models.ForeignKey(Sensores, on_delete=models.CASCADE)

class Semillero(models.Model):
    responsable = models.CharField(max_length=50)
    telefono = models.IntegerField()
    kit = models.ForeignKey(Kit, on_delete=models.CASCADE)
    colegio = models.ForeignKey(Colegio, on_delete=models.CASCADE)

    def __str__(self):
        return self.responsable

class Integrantes(models.Model):

    nombre = models.CharField(max_length=50)
    telefono = models.IntegerField()
    semillero = models.ForeignKey(Semillero, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre

project_module3/app_praes/views.py
from django.shortcuts import render
import paho.mqtt.publish as publish
from .models import Temperatura

# Create your views here.
def index(request):
    respuesta = {}
    return render(request, "app_praes/index.html", respuesta)

def medicion_actual(request):
    respuesta = {}
    return render(request, "app_praes/medicion_actual.html", respuesta)

def monitoreo_lecturas(request):
    temp = Temperatura.objects.all()
    temperatura = temp.values("fecha", "valor")
    respuesta = {"temperatura": temperatura}
    return render(request, "app_praes/monitoreo_lecturas.html", respuesta)

def control_ESP32(request):
    
    topico = "UIS/LP/213"
    IP_broker = "34.73.25.149"
    usuario_broker = "pi"
    password_broker = "raspberry"
    publish.single(topico, "ESP32-LED", port=1883, hostname=IP_broker,
    auth={"username": usuario_broker, "password":password_broker})
    respuesta = {}
    return render(request, "app_praes/control_ESP32.html", respuesta)

project_module3/templates/app_praes/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>KIT PRAES</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="{% static 'js/jquery-3.1.1.min.js'%}"></script>

</head>
<body>

<div class="container">
   <ul class="nav ">
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'main-index' %}"> <img src= "{% static 'centrotic.png' %}" alt="Imagen no encontrada" width=100px height=70px> </a>
  </li>
    <li class="nav-item">
    <a class="nav-link active" href="#">PRAES</a>
  </li>
      <li class="nav-item">
    <a class="nav-link active" href="{% url 'app_praes:medicion-actual'%}">Variables ambientales</a>
  </li>
     <li class="nav-item">
    <a class="nav-link active" href="{% url 'app_praes:monitoreo-lecturas'%}">Monitoreo Lecturas</a>
  </li>
  
       <li class="nav-item">
    <a class="nav-link active" href="{% url 'app_praes:control-kit'%}">Control KIT ambiental</a>
  </li>

 {% if user.is_authenticated %}
    <li class="nav-item"> <a class="nav-link" href="{% url 'logout' %}">SALIR</a> </li>
    {% else %}
    <li class="nav-item"> <a class="nav-link" href="{% url 'login' %}"> INGRESAR</a></li>
    
    {% endif %}
 </ul>
</div>


    {% block body_block %}
    
    {% endblock  %}
</body>
</html>

project_module3/templates/app_praes/comportamiento_historico.html
{% extends "app_praes/base.html" %}
{% block body_block %}



{% endblock  %}

project_module3/templates/app_praes/control_ESP32.html
{% extends "app_praes/base.html" %}
{% load static %}

{% block body_block %}
<div class="container">
    <h1>Control del kit ambiental</h1>
    <div class="row">
        <div class="col-sm">
            <p>{% lorem 2 %}</p>
            <img src="{% static 'esp32.jpeg' %}" alt="Imagen no encontrada" width="300px" height="250px">
        </div>

    </div>

</div>
{% endblock  %}

project_module3/templates/app_praes/index.html
{% extends "app_praes/base.html" %}
{% load static %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h1>PRAES (Proyecto Ambiental Escolar)</h1>
      </div>

<div class="row">

    <div class="col-sm">
    <h3>Proyecto Ambiental Escolar</h3>
    </div>

    <div class="col-sm">
    {% lorem 3 %}
    </div>

</div>
</div>
{% endblock  %}

project_module3/templates/app_praes/medicion_actual.html
{% extends "app_praes/base.html" %}
{% load static %}
{% block body_block %}

<div class="container">
<h1> Última medición</h1> 

<div class="row">
    <div class=col>
        <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action">Temperatura</a>
        <a href="#" class="list-group-item list-group-item-action">Humedad Relativa</a>
        <a href="#" class="list-group-item list-group-item-action">Monóxido de Carbono CO</a>
        <a href="#" class="list-group-item list-group-item-action">Dióxido de Carbono CO2</a>
        <a href="#" class="list-group-item list-group-item-action">Metano CH4</a>
        <a href="#" class="list-group-item list-group-item-action">Material particulado PM2.5- PM10</a>
        <a href="#" class="list-group-item list-group-item-action">Partículas de polvo</a>
        <a href="#" class="list-group-item list-group-item-action">Velocidad del viento</a>
        <a href="#" class="list-group-item list-group-item-action">Dióxido de Azufre SO2</a>
        <a href="#" class="list-group-item list-group-item-action">Dióxido de Nitrógeno NO2</a>
        <a href="#" class="list-group-item list-group-item-action">Ozono O3</a>
        <a href="#" class="list-group-item list-group-item-action">Presión Atmosférica</a>
        <a href="#" class="list-group-item list-group-item-action">Material Orgánico</a>
        <a href="#" class="list-group-item list-group-item-action">Luz Ultravioleta</a>
        <a href="#" class="list-group-item list-group-item-action">Propano</a>
        </div>
    </div>

    <div class="col">
    {% lorem 1 %}
    </div>
</div>

</div>

{% endblock  %}

project_module3/templates/app_praes/monitoreo_lecturas.html
{% extends "app_praes/base.html" %}
{% load static %}

{% block body_block %}
<div class="container">
    <h1>Monitoreo lecturas del KIT</h1>
    <div class="row">
        <div class="col-sm">
        <ul>
        {% for temp in temperatura %}
        <li>
        {{ temp.fecha }} {{ temp.valor }}
        
        </li>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock  %}