project_module3/E3Tratos/urls.py
from django.urls import path 
from .apiviews import VariablesAPI
from .views import index, datos_json

app_name = "E3Tratos"

urlpatterns = [
        path("variables-api", VariablesAPI.as_view(),name="e3tratos-api"),
        path("index", index, name="index-E3Tratos"),
        path("datos-json", datos_json, name="datos-json-E3Tratos"),
]

project_module3/app_praes/urls.py
from django.urls import path 
from rest_framework.authtoken import views
from .apiviews import TemperaturaAPI, HumedadAPI, PresionAtmosfericaAPI, MaterialParticuladoAPI, \
                      NO2API, PolvoAPI, O3API, SO2API, COAPI, CO2API, MetanoPropanoCOAPI, \
                      LuzUVAPI, MaterialOrganicoAPI, CH4API, AnemometroAPI, \
                      CrearUsuarioAPI, LoginView, SensoresAPI

from rest_framework_swagger.views import get_swagger_view
from .views import index, medicion_actual, monitoreo_lecturas, control_ESP32

app_name = "app_praes"
schema_view = get_swagger_view(title='Estructura API')

urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('usuario/', CrearUsuarioAPI.as_view(), name="crear-usuario"),
    path('docs/', schema_view, name="documentacion"),
    path('temperatura/', TemperaturaAPI.as_view(), name="praes-temperatura"),
    path('humedad/', HumedadAPI.as_view(), name="praes-humedad"),
    path('presion-atmosferica/', PresionAtmosfericaAPI.as_view(), name="praes-presion-atmosferica"),
    path('material-particulado/', MaterialParticuladoAPI.as_view(), name="praes-material-particulado"),
    path('no2/', NO2API.as_view(), name="praes-no2"),
    path('polvo/', PolvoAPI.as_view(), name="praes-polvo"),
    path('o3/', O3API.as_view(), name="praes-o3"),
    path('so2/', SO2API.as_view(), name="praes-so2"),
    path('co/', COAPI.as_view(), name="praes-co"),
    path('co2/', CO2API.as_view(), name="praes-co2"),
    path('metano-propano-co/', MetanoPropanoCOAPI.as_view(), name="praes-metano-propano-co"),
    path('luz-uv/', LuzUVAPI.as_view(), name="praes-luz-uv"),
    path('material-organico/', MaterialOrganicoAPI.as_view(), name="praes-material-organico"),
    path('ch4/', CH4API.as_view(), name="praes-ch4"),
    path('anemometro/', AnemometroAPI.as_view(), name="praes-anemometro"),
    path('index/', index, name="index-praes"),
    path('medicion_actual/', medicion_actual, name="medicion-actual"),
    path('monitoreo_lecturas/', monitoreo_lecturas, name="monitoreo-lecturas"),
    path('control_kit/', control_ESP32, name="control-kit"),
    path('sensores/', SensoresAPI.as_view(), name="sensores-API"),
]

project_module3/app_sensado/urls.py
from django.urls import path 
from . import views
from . import apiviews

app_name = "app_sensado"
urlpatterns = [
    path("accion_raspberry", views.accion_raspberry, name="accion-raspberry"),
    path("presentacion-datos", views.presentacion_datos, name="datos-fecha"),
    path("presentacion-datos-json", views.presentacion_datos_json, name="datos-json"),
    path('sensores-generic/', apiviews.ListaSensores_generics.as_view(), name="lista-sensores-generics"),
    path("sensores-generic/<int:pk>/", apiviews.ListaSensores.as_view()), 
    path('tarjetas-generic/', apiviews.ListaTarjetas_generics.as_view(), name="lista-tarjetas-generics"),
    path('tarjetas-generic/<int:pk>/', apiviews.ListaTarjetas.as_view()),
    path('lista-temperaturas/', apiviews.ListaTemperaturas.as_view()),
    path('lista-gases/', apiviews.ListaGases.as_view()),
    path('historico-datos/', views.historico_datos, name="historico-datos"),
    path('historico-datos-json/', views.historico_datos_json, name="historico-datos-json"),
    path('index/', views.index, name="index"),
]

project_module3/nariz_electronica/urls.py
from django.urls import path 
from . import views

app_name = "nariz_electronica"
urlpatterns = [
    path("index", views.index, name="index-nariz"),
]

project_module3/paws/urls.py
from django.urls import path 
from . import views

app_name = "paws"
urlpatterns = [
    path("index", views.index, name="index-paws"),
    path("register", views.register, name="register"),
]

project_module3/project_module3/urls.py
from django.contrib import admin
from django.urls import path, include
from app_sensado import views


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('app_sensado/', include('app_sensado.urls', namespace='app_sensado')),
    path('app_praes/', include('app_praes.urls', namespace="app_praes")),
    path('paws/', include('paws.urls', namespace="paws")),
    path('nariz_electronica/', include('nariz_electronica.urls', namespace="nariz_electronica")),
    path('E3Tratos/', include('E3Tratos.urls', namespace="E3Tratos")),
    path('', views.main_index, name='main-index'),
    path('accounts/', include('django.contrib.auth.urls')),
]

project_module3/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Demo IoT</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

</head>
<body>

<div class="container">
   <ul class="nav ">
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'index' %}">Principal</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'app_sensado:accion-raspberry' %}">Encender LED</a>
  </li>
  <li class="nav-item"> <a class="nav-link" href="{% url 'app_sensado:datos-fecha' %}">Ultimos datos </a>
</li>
  <li class="nav-item"> <a class="nav-link" href="{% url 'app_sensado:historico-datos' %}">Histórico datos</a>
</li>
  <li>Django Rest-Framework
      <a class="nav-link" href="{% url 'app_sensado:lista-sensores-generics' %}">Lista sensores</a>
      <a class="nav-link" href="{% url 'app_sensado:lista-tarjetas-generics' %}">Lista tarjetas</a>
  </li>
</li>
</ul>
</div>


    {% block body_block %}
    
    {% endblock  %}
</body>
</html>

project_module3/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h1>Demo IoT</h1>
        <div class="col">
            <img src="{% static 'IoTdemo.png' %}" class="img-fluid" alt="Responsive image" height=300px width=500px>
        </div>
    </div>
   <p>En el enlace de github puede descargar este proyecto junto con la programación de todas las actividades del diplomado en IoT</p>
   <div class="alert alert-primary" role="alert">
   <a href="https://github.com/LuisDiazM/Demo_IoT" class="alert-link">Enlace Github del proyecto</a>
  </div> 
   <div class="row">
        <div class="col">
            <h2>Modulo I</h2>
            <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSQdDFY1ghiOVRaBZeXHefPBifhlZFrXzf_6qktCEnVDMhV_--zlhkhaiGxoKlmQKdEMwfWf4eSBVEO/embed?start=false&loop=false&delayms=3000" frameborder="0" width="500" height="389" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
        </div>
        <div class="col">
            <h2>Modulo II</h2>
            <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vS9BzWqVHKKTIzb3Ri2dPVaU-OAOyDaWn_iIJzTye4E1e0I1mb1KV0MwYiimZHE-nxHCk1eTE2iDZ6m/embed?start=false&loop=false&delayms=3000" frameborder="0" width="500" height="389" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
        </div>
        <div class="col">
            <h2>Modulo III</h2>
            <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vR5K8BHyYsPcZ3QxSoDHUZIbrxdcAZVztzwYeTp9o8EpaVT3pFyf7JwAsgP_Nm20621q8FG0W6cmx-4/embed?start=false&loop=false&delayms=3000" frameborder="0" width="500" height="389" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>  
        </div>


    </div>

</div>
{% endblock  %}

project_module3/templates/main_base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>CENTROTIC</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>


</head>
<body>

<div class="container">
<div class="jumbotron">
<h3> Proyectos </h3>
 <a class="nav-link active" href="{% url 'main-index' %}"> <img src= "{% static 'centrotic.png' %}" alt="Imagen no encontrada" width=150px height=120px> </a>    
</div>
<ul class="nav ">
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'app_sensado:index' %}">Diplomado IoT</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'app_praes:index-praes'%}">PRAES</a>
    </li>
    <li class="nav-item"> <a class="nav-link" href="{% url 'paws:index-paws' %}">Proyecto PAWS</a>
  </li>
  <li class="nav-item"> <a class="nav-link" href="http://centrotic2uis.cloudapp.net:8080/sigripv/"> Sistemas GRIPV</a> </li>
   <li class="nav-item"> <a class="nav-link" href="{% url 'nariz_electronica:index-nariz' %}">Nariz Electronica</a> </li>
  <li class="nav-item"> <a class="nav-link" href="{% url 'E3Tratos:index-E3Tratos' %}">E3Tratos</a> </li>

  
   {% if user.is_authenticated %}
    <li class="nav-item"> <a class="nav-link" href="{% url 'logout' %}">SALIR</a> </li>
    {% else %}
    <li class="nav-item"> <a class="nav-link" href="{% url 'login' %}"> INGRESAR</a></li>
    
    {% endif %}
  </ul>
  </ul>
</div>




    {% block body_block %}
    
    {% endblock  %}
  <br>  <br>   <br>
  <br>


   <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-sm-6 footerleft ">
            <h4> <b>Proyectos de Investigación asociados al grupo de investigación Radiogis</b></h4>
            <p><i class="fa fa-map-pin"></i> Bucaramanga, Santander, Colombia</p>
            <p><i class="fa fa-phone"></i> PBX : (57) (7) 6344000 ext. 2373</p>
            <p><i class="fa fa-envelope"></i> E-mail : luismiguel@radiogis.uis.edu.co</p>
               {% if user.is_authenticated %}
               <h4> Solo Usuario Administrador </h4>
               <ul>
                 <li><a href="{% url 'app_praes:sensores-API' %}">Sensores API</a></li>
                 <li>                <a href="{% url 'app_praes:login' %}">Usuarios API</a>                 </li>
                 <li>                <a href="{% url 'app_praes:crear-usuario' %}">Crear Usuario</a>        </li>
                 <li>                <a href="{% url 'app_praes:documentacion' %}">Documentacion</a>        </li>
               </ul>
                
             {% else %}
              <a href="{% url 'admin:index' %}">Ingresar al sitio Administrador</a>
    
              {% endif %}


          </div>
            <h4 class="heading7">Productos</h4>
            <ul class="footer-ul">
              <li>Nariz Electrónica</li>
              <li>Desarrollo diplomado IOT</li>
              <li>Sistemas GRIPV</li>
              <li>Proyectos Ambientales Escolares (PRAES)</li>
              <li>Protocolo PAWS con SDR</li>

            </ul>
          </div>

        </div>
      </div>
</footer>
</body>
</html>

project_module3/templates/main_index.html
{% extends "main_base.html" %}
{% load static %}
{% block body_block %}
<div class="container">

    <div class="row">
        <div class="col-sm">
        {% if user.is_authenticated %}
        <h1>Hola {{user.username}} </h1>
        {% else %}
        {% endif %}
            {% lorem 2 %}
        </div>
        <div class="col-sm">
            {% lorem 2 %}
        </div>
    </div>

</div>
{% endblock  %}