project_module3/paws/urls.py
from django.urls import path 
from . import views

app_name = "paws"
urlpatterns = [
    path("index", views.index, name="index-paws"),
    path("register", views.register, name="register"),
]

project_module3/project_module3/urls.py
from django.contrib import admin
from django.urls import path, include
from app_sensado import views


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('app_sensado/', include('app_sensado.urls', namespace='app_sensado')),
    path('app_praes/', include('app_praes.urls', namespace="app_praes")),
    path('paws/', include('paws.urls', namespace="paws")),
    path('nariz_electronica/', include('nariz_electronica.urls', namespace="nariz_electronica")),
    path('E3Tratos/', include('E3Tratos.urls', namespace="E3Tratos")),
    path('', views.main_index, name='main-index'),
    path('accounts/', include('django.contrib.auth.urls')),
]

project_module3/paws/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField

# Create your models here.


class Point(models.Model):
    latitude = models.CharField(max_length=25)
    longitude = models.CharField(max_length=25)

class Ellipse(models.Model):
    semiMajorAxis = models.FloatField()
    semiMinorAxis = models.FloatField()
    orientation = models.FloatField()
    center = models.ForeignKey(Point, on_delete=models.CASCADE)


class Geolocation(models.Model):
    """
    Para expresar las coordenadas en unidades de grados y metros
    """
    point = models.ForeignKey(Ellipse, on_delete=models.CASCADE)
    confidence = models.IntegerField(default=95)


class AntennaCharacteristics(models.Model):
    """
    AGL: Above Ground Level (default)
    AMSL: Above Mean Sea Level)
    """
    height = models.FloatField()
    AGL = "AGL"
    AMSL = "AMSL"
    enum_heigtType =  ((AGL, "Above Ground Level"), (AMSL, "AMSL: Above Mean Sea Level"))
    heightType = models.CharField(max_length=50, choices=enum_heigtType, default=AGL)
    antenna_direction = models.CharField(max_length=20, blank=True)
    antenna_radiation_pattern = models.CharField(max_length=15, blank=True)
    antenna_gain = models.FloatField(blank=True)

class FrequencyRange(models.Model):
    """
    Provee informacion adicional que puede ayudar a determinal la disponibilidad del espectro,
    provee las frecuencias en las que el dispositivo puede operar
    """
    startHz = models.FloatField()
    stopHz = models.FloatField()

class DeviceCapabilities(models.Model):
    frequencyRanges = models.ForeignKey(FrequencyRange, on_delete=models.CASCADE)


class DeviceDescriptor(models.Model):
    """
    Contiene parametros para identificar el dispositivo especifico

    """
    serialNumber = models.CharField(max_length=25)
    manufacturerId = models.CharField(max_length=25)
    modelId = models.CharField(max_length=25)
    rulesetIds = JSONField()
    anttenna_characteristics = models.ForeignKey(AntennaCharacteristics, on_delete=models.CASCADE)
    devicecapabilities = models.ForeignKey(DeviceCapabilities, on_delete=models.CASCADE)
    geolocation = models.ForeignKey(Geolocation, on_delete=models.CASCADE)

class DeviceOwner(models.Model):
    """
    Provee informacion de los propietarios
    """
    owner = JSONField()
    operator = JSONField()
    devicedescriptor = models.ForeignKey(DeviceDescriptor, on_delete=models.CASCADE)

class RulsetInfo(models.Model):
    """
    Contiene las reglas de dominio del ente regulador
    """
    authority = models.CharField(max_length=50)
    rulsetId = models.CharField(max_length=50)
    maxLocationChange = models.FloatField(blank=True)
    maxPollingSecs = models.FloatField(blank=True)


class EventTime(models.Model):
    """ Indica el periodo de tiempo sobre el cual el espectro
    es valido
    """
    startTime = models.DateTimeField(auto_now=False, auto_now_add=False)
    stopTime = models.DateTimeField(auto_now=False, auto_now_add=False)

class Spectrum(models.Model):
    resolutionBwHz = models.FloatField()
    profiles = JSONField()
    geolocation = models.ForeignKey(Geolocation, on_delete=models.CASCADE)

class SpectrumProfilePoint(models.Model):
    hz = models.FloatField()
    dbm = models.FloatField()
    
class SpectrumProfile(models.Model):
    """Se caracteriza por una lista ordenada de la potencia maxima permitida
    """
    list1= models.ForeignKey(SpectrumProfilePoint, on_delete=models.CASCADE)
    rulsetinfo = models.ForeignKey(RulsetInfo, on_delete=models.CASCADE)


class SpectrumSchedule(models.Model):
    """Indica el periodo de tiempo sobre el cual ese espectro esta disponible
    """
    eventTime = models.ForeignKey(EventTime, on_delete=models.CASCADE)
    spectrum = models.ForeignKey(Spectrum, on_delete=models.CASCADE)


class SpectrumSpec(models.Model):
    """Muestra la disponibilidad de espectro para un conjunto de reglas
    """
    rulsetInfo = models.ForeignKey(RulsetInfo, on_delete=models.CASCADE)
    spectrumSchedules = models.ForeignKey(SpectrumSchedule, on_delete=models.CASCADE)
    timeRange = models.ForeignKey(EventTime, on_delete=models.CASCADE)
    frequencyRanges = JSONField(encoder="")
    needsSpectrumReport = models.BooleanField()
    maxTotalBwHz = models.FloatField(blank=True)
    maxContiguousBwHz = models.FloatField(blank=True)
    geolocation = models.ForeignKey(Geolocation, on_delete=models.CASCADE)

class DeviceValidity(models.Model):
    deviceDesc = models.ForeignKey(DeviceDescriptor, on_delete=models.CASCADE)
    isValid = models.BooleanField()
    reason = models.CharField(max_length=150)

project_module3/paws/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    respuesta = {}
    return render(request, "paws/index.html", respuesta)

def register(request):
    respuesta = {}
    return render(request, "paws/register.html", respuesta)

project_module3/templates/paws/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Protocolo PAWS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

</head>
<body>

<div class="container">
   <ul class="nav ">
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'main-index' %}"> <img src= "{% static 'centrotic.png' %}" alt="Imagen no encontrada" width=100px height=70px> </a>
  </li>
    <li class="nav-item">
    <a class="nav-link active" href="#">Consulta dispositivos esclavos</a>
  </li>
      <li class="nav-item">
    <a class="nav-link active" href="#">Canales libres por regiones</a>
  </li>
   {% if user.is_authenticated %}
    <li class="nav-item"> <a class="nav-link" href="{% url 'paws:register' %}">Registrar SDR esclavos</a> </li>

    <li class="nav-item"> <a class="nav-link" href="{% url 'logout' %}">SALIR</a> </li>
    {% else %}
    <li class="nav-item"> <a class="nav-link" href="{% url 'login' %}"> INGRESAR</a></li>
    
    {% endif %}
 </ul>
</div>


    {% block body_block %}
    
    {% endblock  %}
</body>
</html>

project_module3/templates/paws/index.html
{% extends "paws/base.html" %}
{% load static %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h1>Protocolo PAWS usando SDR</h1>
      </div>

<div class="row">

    <div class="col-9">
    <h3>Modelo general de la base de datos de PAWS</h3>
        <img src="{% static 'modelo-base-datos.png' %}" alt="imagen no encontrada" height="550px" width="800px">
    <h3> Modelo de comunicación del protocolo PAWS implementado</h3>
        <img src="{% static 'modelo_comunicacion.jpg' %}" alt="imagen no encontrada" height="450px" width="600px">

    </div>
    <div class="col-sm">
        {% lorem 3 %}
    </div>

</div>
</div>
{% endblock  %}

project_module3/templates/paws/register.html
{% extends "paws/base.html" %}
{% load static %}

{% block body_block %}

<div class="container">
    <h1>Registro de dispositivos esclavos</h1>
    <div class="row">
        <div class="col-sm">
        <img src="{% static 'Secuencia_comunicacion.png' %}" alt="imagen no encontrada">
        </div>

        <div class="col-sm">
          <form>
  <div class="form-group">
    <label for="numero-serial">Número Serial</label>
    <input type="text" class="form-control" id="numero-serial" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

        </div>
    </div>
</div>

{% endblock  %}