project_module3/E3Tratos/urls.py
from django.urls import path 
from .apiviews import VariablesAPI
from .views import index, datos_json

app_name = "E3Tratos"

urlpatterns = [
        path("variables-api", VariablesAPI.as_view(),name="e3tratos-api"),
        path("index", index, name="index-E3Tratos"),
        path("datos-json", datos_json, name="datos-json-E3Tratos"),
]

project_module3/paws/urls.py
from django.urls import path 
from . import views

app_name = "paws"
urlpatterns = [
    path("index", views.index, name="index-paws"),
    path("register", views.register, name="register"),
]

project_module3/project_module3/urls.py
from django.contrib import admin
from django.urls import path, include
from app_sensado import views


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('app_sensado/', include('app_sensado.urls', namespace='app_sensado')),
    path('app_praes/', include('app_praes.urls', namespace="app_praes")),
    path('paws/', include('paws.urls', namespace="paws")),
    path('nariz_electronica/', include('nariz_electronica.urls', namespace="nariz_electronica")),
    path('E3Tratos/', include('E3Tratos.urls', namespace="E3Tratos")),
    path('', views.main_index, name='main-index'),
    path('accounts/', include('django.contrib.auth.urls')),
]

project_module3/E3Tratos/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField


# Create your models here.
class Variables(models.Model):
    """
    Esta clase hace referencia a las variables guardadas en JSON
    """
    variables = JSONField()
    fecha = models.DateTimeField(auto_now=False, auto_now_add=False, blank=True)

project_module3/E3Tratos/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from .models import Variables

# Create your views here.
def index(request):
    respuesta = {}
    return render(request, "E3Tratos/index.html", respuesta)

@csrf_exempt
def datos_json(request):
    var = Variables.objects.all()
    datos = var.values("fecha", "variables")
    datos = list(map(lambda datos: [datos["fecha"], datos["variables"]], datos))

    respuesta = {"datos": datos}
    return JsonResponse(respuesta)

project_module3/templates/E3Tratos/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>E3Tratos</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

</head>
<body>

<div class="container">
   <ul class="nav ">
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'main-index' %}"> <img src= "{% static 'centrotic.png' %}" alt="Imagen no encontrada" width=100px height=70px> </a>
  </li>
   <li class="nav-item">
    <a class="nav-link" href="{% url 'E3Tratos:e3tratos-api' %}">API ENVIAR DATOS</a>
  </li> 
    <li class="nav-item">
    <a class="nav-link" href="{% url 'E3Tratos:datos-json-E3Tratos' %}">RECIBIR DATOS </a>
  </li>  
</ul>
</div>


    {% block body_block %}
    
    {% endblock  %}
</body>
</html>

project_module3/templates/E3Tratos/index.html
{% extends "E3Tratos/base.html" %}
{% load static %}

{% block body_block %}
<div class="container">
<h1> E3Tratos UIS </h1>

<p> Acá puede colocar el contenido de las pagina, en la carpeta static puede colocar los css y javascript,
para usarlos mire el siguiente ejemplo: </p>

<p> Los hipervinculos que coloqué en base.html son para que sepa que la API de subida y la descarga de datos</p>

<img src="{% static 'E3Tratos/globo_demo.jpg' %}" alt="Imagen no encontrada">


</div>
{% endblock  %}